// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.4
// source: chat_rpc.proto

package chat_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserChatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SendUserId uint32 `protobuf:"varint,1,opt,name=send_user_id,json=sendUserId,proto3" json:"send_user_id,omitempty"`
	RevUserId  uint32 `protobuf:"varint,2,opt,name=rev_user_id,json=revUserId,proto3" json:"rev_user_id,omitempty"`
	Msg        []byte `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`                              // msg的json格式 msgPreview通过msg和system_msg算出
	SystemMsg  []byte `protobuf:"bytes,4,opt,name=system_msg,json=systemMsg,proto3" json:"system_msg,omitempty"` // 系统消息
}

func (x *UserChatRequest) Reset() {
	*x = UserChatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserChatRequest) ProtoMessage() {}

func (x *UserChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserChatRequest.ProtoReflect.Descriptor instead.
func (*UserChatRequest) Descriptor() ([]byte, []int) {
	return file_chat_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *UserChatRequest) GetSendUserId() uint32 {
	if x != nil {
		return x.SendUserId
	}
	return 0
}

func (x *UserChatRequest) GetRevUserId() uint32 {
	if x != nil {
		return x.RevUserId
	}
	return 0
}

func (x *UserChatRequest) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *UserChatRequest) GetSystemMsg() []byte {
	if x != nil {
		return x.SystemMsg
	}
	return nil
}

type UserChatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *UserChatResponse) Reset() {
	*x = UserChatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserChatResponse) ProtoMessage() {}

func (x *UserChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserChatResponse.ProtoReflect.Descriptor instead.
func (*UserChatResponse) Descriptor() ([]byte, []int) {
	return file_chat_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *UserChatResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_chat_rpc_proto protoreflect.FileDescriptor

var file_chat_rpc_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x72, 0x70, 0x63, 0x22, 0x84, 0x01, 0x0a, 0x0f, 0x55,
	0x73, 0x65, 0x72, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20,
	0x0a, 0x0c, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x1e, 0x0a, 0x0b, 0x72, 0x65, 0x76, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x72, 0x65, 0x76, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x6d, 0x73, 0x67,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d, 0x73,
	0x67, 0x22, 0x2b, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x32, 0x4c,
	0x0a, 0x05, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x43, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x72, 0x70, 0x63,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a,
	0x2e, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_chat_rpc_proto_rawDescOnce sync.Once
	file_chat_rpc_proto_rawDescData = file_chat_rpc_proto_rawDesc
)

func file_chat_rpc_proto_rawDescGZIP() []byte {
	file_chat_rpc_proto_rawDescOnce.Do(func() {
		file_chat_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_chat_rpc_proto_rawDescData)
	})
	return file_chat_rpc_proto_rawDescData
}

var file_chat_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_chat_rpc_proto_goTypes = []any{
	(*UserChatRequest)(nil),  // 0: chat_rpc.UserChatRequest
	(*UserChatResponse)(nil), // 1: chat_rpc.UserChatResponse
}
var file_chat_rpc_proto_depIdxs = []int32{
	0, // 0: chat_rpc.Users.UserCreate:input_type -> chat_rpc.UserChatRequest
	1, // 1: chat_rpc.Users.UserCreate:output_type -> chat_rpc.UserChatResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chat_rpc_proto_init() }
func file_chat_rpc_proto_init() {
	if File_chat_rpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chat_rpc_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*UserChatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_rpc_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*UserChatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chat_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_rpc_proto_goTypes,
		DependencyIndexes: file_chat_rpc_proto_depIdxs,
		MessageInfos:      file_chat_rpc_proto_msgTypes,
	}.Build()
	File_chat_rpc_proto = out.File
	file_chat_rpc_proto_rawDesc = nil
	file_chat_rpc_proto_goTypes = nil
	file_chat_rpc_proto_depIdxs = nil
}
