// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"im_server/im_user/user_api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/user/friend_info",
				Handler: friendInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/friends",
				Handler: friendListHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/user/friends",
				Handler: friendNoticeUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/search",
				Handler: searchHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/user_info",
				Handler: UserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/user/user_info",
				Handler: UserInfoUpdateHandler(serverCtx),
			},
		},
	)
}
