// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"im_server/im_logs/logs_api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/logs/logs",
					Handler: logListHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/logs/logs",
					Handler: logRemoveHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/logs/logs/:id",
					Handler: logReadHandler(serverCtx),
				},
			}...,
		),
	)
}
