// Code generated by goctl. DO NOT EDIT.
package types

type LoginInfo struct {
	Token string `json:"token"`
}

type LoginRequest struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Code int       `json:"code"`
	Data LoginInfo `json:"data"`
	Msg  string    `json:"msg"`
}

type OpenLoginInfo struct {
	Name string `json:"name"`
	Icon string `json:"icon"`
	Href string `json:"href"` // 跳转地址
}

type OpenLoginInfoResponse struct {
	Code int             `json:"code"`
	Data []OpenLoginInfo `json:"data"`
	Msg  string          `json:"msg"`
}

type Response struct {
	Code int    `json:"code"`
	Data string `json:"data"`
	Msg  string `json:"msg"`
}
