// Code generated by goctl. DO NOT EDIT.
package types

type UserInfoRequest struct {
	UserID uint `header:"User-ID"`
	Role   int8 `header:"Role"`
}

type UserInfoResponse struct {
	UserID         uint   `json:"userID`
	NickName       string `json:"nickName`
	Role           int8   `json:"role`
	Abstract       string `json:"abstract"`
	Avatar         string `json:"avatar"`
	RegisterSource string `json:"registerSource"` // 注册来源
}
