// Code generated by goctl. DO NOT EDIT.
package types

type ChatHistoryRequest struct {
	UserID uint `header:"User-ID"`
	Page   int  `form:"page"`
	Limit  int  `form:"limit"`
}

type ChatHistoryResponse struct {
	ID        uint   `json:"id"`
	UserID    uint   `json:"userID"`
	Avatar    string `json:"avatar"`
	Nickname  string `json:"nickname"`
	CreatedAt string `json:"createdAt"`
}
