// Code generated by goctl. DO NOT EDIT.
package types

type ChatHistoryRequest struct {
	UserID   uint `header:"User-ID"`
	Page     int  `form:"page,optional"`
	Limit    int  `form:"limit,optional"`
	FriendID uint `form:"friendID"` // 好友ID
}

type ChatHistoryResponse struct {
	ID        uint   `json:"id"`
	UserID    uint   `json:"userID"`
	Avatar    string `json:"avatar"`
	Nickname  string `json:"nickname"`
	CreatedAt string `json:"createdAt"`
}

type ChatSession struct {
	UserID     uint   `json:"userID"`
	Avatar     string `json:"avatar"`
	Nickname   string `json:"nickname"`
	CreatedAt  string `json:"createdAt"`  // 消息时间
	MsgPreview string `json:"msgPreview"` // 消息预览
	IsTop      bool   `json:"isTop"`      // 是否置顶
}

type ChatSessionRequest struct {
	UserID uint   `header:"User-ID"`
	Page   int    `form:"page,optional"`
	Limit  int    `form:"limit,optional"`
	Key    string `form:"key,optional"`
}

type ChatSessionResponse struct {
	List  []ChatSession `json:"list"`
	Count int64         `json:"count"`
}

type ChatDeleteRequest struct {
	UserID uint   `header:"User-ID"`
	IdList []uint `json:"idList"`
}

type ChatDeleteResponse struct {
}

type UserTopRequest struct {
	UserID   uint `header:"User-ID"`
	FriendID uint `json:"friendID"`
}

type UserTopResponse struct {
}
