// Code generated by goctl. DO NOT EDIT.
// Source: chat_rpc.proto

package server

import (
	"context"

	"im_server/im_chat/chat_rpc/internal/logic"
	"im_server/im_chat/chat_rpc/internal/svc"
	"im_server/im_chat/chat_rpc/types/chat_rpc"
)

type ChatServer struct {
	svcCtx *svc.ServiceContext
	chat_rpc.UnimplementedChatServer
}

func NewChatServer(svcCtx *svc.ServiceContext) *ChatServer {
	return &ChatServer{
		svcCtx: svcCtx,
	}
}

func (s *ChatServer) UserChat(ctx context.Context, in *chat_rpc.UserChatRequest) (*chat_rpc.UserChatResponse, error) {
	l := logic.NewUserChatLogic(ctx, s.svcCtx)
	return l.UserChat(in)
}
