// Code generated by goctl. DO NOT EDIT.
// Source: chat_rpc.proto

package server

import (
	"context"

	"im_server/im_chat/chat_rpc/internal/logic"
	"im_server/im_chat/chat_rpc/internal/svc"
	"im_server/im_chat/chat_rpc/types/chat_rpc"
)

type UsersServer struct {
	svcCtx *svc.ServiceContext
	chat_rpc.UnimplementedUsersServer
}

func NewUsersServer(svcCtx *svc.ServiceContext) *UsersServer {
	return &UsersServer{
		svcCtx: svcCtx,
	}
}

func (s *UsersServer) UserCreate(ctx context.Context, in *chat_rpc.UserChatRequest) (*chat_rpc.UserChatResponse, error) {
	l := logic.NewUserCreateLogic(ctx, s.svcCtx)
	return l.UserCreate(in)
}
